# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-3.11

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- HTTP-4000.2.22
- MonadRandom-0.4.1
- SHA-1.6.4.2
- StateVar-1.1.0.1
- attoparsec-0.13.0.1
- base-orphans-0.4.4
- base64-bytestring-1.0.0.1
- bifunctors-5.1
- blaze-builder-0.4.0.1
- bzlib-0.5.0.5
- case-insensitive-1.2.0.5
- comonad-4.2.7.2
- contravariant-1.3.3
- data-binary-ieee754-0.4.4
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.4.4
- dlist-0.7.1.2
- either-4.4.1
- entropy-0.3.7
- exceptions-0.8.0.2
- free-4.12.1
- ghc-paths-0.1.0.9
- hashable-1.2.3.3
- haste-compiler-0.5.2
- mmorph-1.0.4
- monad-control-1.0.0.4
- monads-tf-0.1.0.2
- mtl-2.2.1
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.9
- prelude-extras-0.4.0.2
- primitive-0.6.1.0
- profunctors-5.1.2
- random-1.1
- scientific-0.3.4.4
- semigroupoids-5.0.0.4
- semigroups-0.18.0.1
- stm-2.4.4
- system-fileio-0.3.16.3
- system-filepath-0.4.13.4
- tagged-0.8.2
- tar-0.4.2.2
- temporary-1.2.0.3
- text-1.2.1.3
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- utf8-string-1.0.1.1
- vector-0.11.0.0
- void-0.7.1
- websockets-0.9.6.1
- ghc-simple-0.1.3
- shellmate-0.1.6
- filesystem-trees-0.1.0.6

# Override default flag values for local packages and extra-deps
flags:
  text:
    integer-simple: false
  tar:
    old-time: false

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
